//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 12:31:36 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://smev.gosuslugi.ru/rev120315", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl.gosuslugi.smev.rev120315;
