//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 12:36:25 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://epgu.gosuslugi.ru/lk/subscribe/types/ElkSubscribeServiceTypes/")
package ru.gosuslugi.epgu.lk.subscribe.types.elksubscribeservicetypes;
