//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.09 at 06:15:32 PM SAMT 
//


package webservice.objects.elk;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Invitations }
     * 
     */
    public Invitations createInvitations() {
        return new Invitations();
    }

    /**
     * Create an instance of {@link CreatePayments }
     * 
     */
    public CreatePayments createCreatePayments() {
        return new CreatePayments();
    }

    /**
     * Create an instance of {@link InvitationResponseItems }
     * 
     */
    public InvitationResponseItems createInvitationResponseItems() {
        return new InvitationResponseItems();
    }

    /**
     * Create an instance of {@link CreateOrder }
     * 
     */
    public CreateOrder createCreateOrder() {
        return new CreateOrder();
    }

    /**
     * Create an instance of {@link Payments }
     * 
     */
    public Payments createPayments() {
        return new Payments();
    }

    /**
     * Create an instance of {@link PaymentResponseItem }
     * 
     */
    public PaymentResponseItem createPaymentResponseItem() {
        return new PaymentResponseItem();
    }

    /**
     * Create an instance of {@link InvitationResponse }
     * 
     */
    public InvitationResponse createInvitationResponse() {
        return new InvitationResponse();
    }

    /**
     * Create an instance of {@link PaymentResponse }
     * 
     */
    public PaymentResponse createPaymentResponse() {
        return new PaymentResponse();
    }

    /**
     * Create an instance of {@link UpdateInvitations }
     * 
     */
    public UpdateInvitations createUpdateInvitations() {
        return new UpdateInvitations();
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link OrderResponseItems }
     * 
     */
    public OrderResponseItems createOrderResponseItems() {
        return new OrderResponseItems();
    }

    /**
     * Create an instance of {@link UpdateOrders }
     * 
     */
    public UpdateOrders createUpdateOrders() {
        return new UpdateOrders();
    }

    /**
     * Create an instance of {@link InvitationResponseItem }
     * 
     */
    public InvitationResponseItem createInvitationResponseItem() {
        return new InvitationResponseItem();
    }

    /**
     * Create an instance of {@link CreateOrdersRequest }
     * 
     */
    public CreateOrdersRequest createCreateOrdersRequest() {
        return new CreateOrdersRequest();
    }

    /**
     * Create an instance of {@link Invitation }
     * 
     */
    public Invitation createInvitation() {
        return new Invitation();
    }

    /**
     * Create an instance of {@link DeleteOrdersRequest }
     * 
     */
    public DeleteOrdersRequest createDeleteOrdersRequest() {
        return new DeleteOrdersRequest();
    }

    /**
     * Create an instance of {@link OrderResponse }
     *
     */
    public OrderResponse createOrderResponse() {
        return new OrderResponse();
    }

    /**
     * Create an instance of {@link CreateInvitations }
     * 
     */
    public CreateInvitations createCreateInvitations() {
        return new CreateInvitations();
    }

    /**
     * Create an instance of {@link StatusHistory }
     * 
     */
    public StatusHistory createStatusHistory() {
        return new StatusHistory();
    }

    /**
     * Create an instance of {@link PaymentResponseItems }
     * 
     */
    public PaymentResponseItems createPaymentResponseItems() {
        return new PaymentResponseItems();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link UpdateOrdersRequest }
     * 
     */
    public UpdateOrdersRequest createUpdateOrdersRequest() {
        return new UpdateOrdersRequest();
    }

    /**
     * Create an instance of {@link UpdateOrder }
     * 
     */
    public UpdateOrder createUpdateOrder() {
        return new UpdateOrder();
    }

    /**
     * Create an instance of {@link OrderResponseItem }
     * 
     */
    public OrderResponseItem createOrderResponseItem() {
        return new OrderResponseItem();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link StatusHistoryList }
     * 
     */
    public StatusHistoryList createStatusHistoryList() {
        return new StatusHistoryList();
    }

    /**
     * Create an instance of {@link CreateOrders }
     * 
     */
    public Orders createCreateOrders() {
        return new Orders();
    }

    public UploadFiles createUploadFiles(){
        return new UploadFiles();
    }

}
