/*
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.09 at 06:15:32 PM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gosuslugi.ru/lk/elk/types/")
package wsdl.lk.elk.types;
*/
package webservice.objects.elk;